---
language: "python"
python: "2.7"

env:
  - SITE_AND_INVENTORY="tests/main.yml -i tests/inventory"

install:
  - "pip install ansible==1.6.2"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_AND_INVENTORY --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    grep -q 'PermitRootLogin no'
    && (echo 'Block root login test: pass' && exit 0)
    || (echo 'Block root login test: fail' && exit 1)
  - >
    grep -q 'PasswordAuthentication no'
    && (echo 'Prevent password authentication test: pass' && exit 0)
    || (echo 'Prevent password authentication test: fail' && exit 1)